name: Keep Render Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s https://mybackend-oftz.onrender.com
